### ISSUE TITLE
range polyfill does not work when loaded via ajax.

### ISSUE THREAD

**Issue by juliandormon** [zoltan-dulac/html5Forms.js#14]
I'm having a problem with the range input polyfill. It works great when I load a page normally, but when I load form elements via ajax, the styling is apparent (the blue dragger ball is visible) but the length of the widget is set to 0. If I manually set the length in firebug after the load, the slider looks perfect but fails to register any input. Is there some kind of callback that I need to make after loading forms via ajax? Thanks so much!!!!! BTW, I am using Firefox version 22 on Windows 7 to test.

**Comment by zoltan-dulac** [comment]
At the moment, this script does not support loading the script via ajax separately from the way html5Forms.js does.  This may be supported in a future release if there is a lot of demand, or if someone takes the initiative to fix this (I don't need this feature myself, and since it dynamically loads scripts as needed anyway, I am not inclined to make this change myself in the near future.
